/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.qhuytu.jthriftfiles.services;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class servicesConstants {

  public static final java.lang.String NOTESERVICE = "NoteService";

}
